### PR TITLE
Added a navigation bar

### PR DESCRIPTION
**Pull request by Aryal-rajiv**
Added a vertical navigation bar which carries needed index as well as social media links. Fontawesome icons need to be added but css for it is already done

### CODE REVIEW

**Comment by inirajan** [comment]
I am just learning so I don't know about that

**Review by inirajan — COMMENTED** [review]
Thank you daii for helping me

**Comment by Aryal-rajiv** [comment]
open source community ma garni nai yei ho. I am too learning so mention not

**Comment by Aryal-rajiv** [comment]
If you feel like my change is helpful please merge it.

**Comment by inirajan** [comment]
i am just learning so i don't know how to merge

**Pull request merged**
